---

- name: Create instance
  hosts: localhost
  tasks:
  - name: Create Instance from api of service catalog 
    uri:
      url: "https://10.18.57.58/api/service_catalogs/1/service_templates/18"
      validate_certs: False
      user: admin
      password: smartvm
      method: POST
      body: {"action": "order"}
      force_basic_auth: yes
      status_code: 200
      body_format: json
       
       
