---

- name: Flavor Deletion
  hosts: localhost
  tasks:
  - name: Delete Flavor from API.
    uri:
      url: "https://10.18.57.58/api/providers/4/flavors/{{ flavor_id}}"
      validate_certs: False
      user: admin
      password: smartvm
      method: POST
      body: {"action":"delete"}
      force_basic_auth: yes
      status_code: 200
      body_format: json
       
       
