- hosts: all
  tasks:
  - name: Install a yum package in Ansible example
    yum:
      name: '{{ package1 }}'
      state: present


  - name: Install a yum package in Ansible example
    yum:
      name: '{{ package2 }}'
      state: present

