
---
- name: Attach a volume to an instance 
  hosts: all
  tasks:

  - name: Launching a volume attachment operation
    set_stats:
      data:
        pb_var1a: "{{ input1a }}"
        pb_var1b: "{{ input1b }}"
  - debug: msg="Hello, {{ input1a }} and {{ input1b }}"
